---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: zookeeper01
    image: amazonlinux
    pre_build_image: no
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
